### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by pierreganty** [ISCAS-PMC/roll-library#3]
Dear maintainers,

I am currently running some experiments with your inclusion checker (i.e. `include` option).
I would like to collect the total runtime for the inclusion check but I am not sure what it is.
Sometimes there is a "Total checking time" in the output but not when learning is involved. 
With learning I see `#TTO`.
So my question is what is a consistent and reliable way to report execution time for checking inclusion 
when running `java -jar ROLL.jar include ...`?

Thank you,
Pierre.

**Comment by liyong31** [comment]
Dear Pierre,
Currently we only report the execution time with #TTO, which is not available when the tool fails.
For a reliable way to report execution time, I suggest you to use benchexec or /usr/bin/time.

Regards,
Yong
